# Generated by Django 3.1.7 on 2021-03-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=100)),
                ('news_text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='Data publikacji')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_about',
            field=models.TextField(),
        ),
    ]
