# Generated by Django 4.0.dev20210315091521 on 2021-03-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_alter_welcome_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Welcome',
        ),
    ]
