# Generated by Django 4.0.dev20210315091521 on 2021-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('welcome', '0003_delete_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_about', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='Data publikacji')),
            ],
        ),
    ]
