# Generated by Django 4.0.dev20210315091521 on 2021-03-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
