# Generated by Django 4.0.dev20210315091521 on 2021-03-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_contactus_remove_aboutus_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='telephone',
        ),
        migrations.AddField(
            model_name='contactus',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
