# Generated by Django 4.0.dev20210315091521 on 2021-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_id_alter_video_id_alter_videoloader_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoLoader',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
