# Generated by Django 4.0.dev20210315091521 on 2021-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_video_video_url_delete_videolesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_content',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
