# Generated by Django 4.0.dev20210315091521 on 2021-03-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_video_video_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
