# Generated by Django 4.0.dev20210315091521 on 2021-03-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_video_video_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_password',
        ),
    ]
